package ipc

// EventClass is the loss-tolerance taxonomy for the run event stream. It is
// the single owner of "may this event be dropped?", so the daemon's overflow
// policy and every consumer's reconciliation policy agree by construction
// rather than by two lists of event names drifting apart.
type EventClass int

const (
	// ClassActivity is ephemeral output with no state effect. Losing it
	// cannot make a consumer render a state the daemon does not hold, so it
	// is the only class that may be dropped under pressure.
	ClassActivity EventClass = iota
	// ClassState is a state transition. Its payload is a wakeup hint only -
	// every field is reconstructable from get_run - but the *fact* that
	// state changed must reach every subscriber, or the consumer keeps
	// rendering state the daemon has already left behind.
	ClassState
	// ClassControl is stream metadata generated by the broker itself, never
	// by the executor. It is delivered ahead of queued payload.
	ClassControl
)

// ClassOf classifies an event type for overflow and reconciliation handling.
//
// Unknown types fail safe to ClassState: an event a future producer adds and
// this build does not recognise is never silently dropped. Only the types
// explicitly named here are droppable.
func ClassOf(t EventType) EventClass {
	switch t {
	case EventLogChunk:
		return ClassActivity
	case EventStreamGap:
		return ClassControl
	default:
		return ClassState
	}
}
